<?php

use Drupal\Core\Menu\MenuTreeParameters;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Form\FormStateInterface;

define( 'gavias_sliderlayer_VERSION', '1.0' );
define( 'GAV_SLIDERLAYER_PATH', drupal_get_path('module', 'gavias_sliderlayer') );
  module_load_include('php','gavias_sliderlayer', '/includes/functions');
  module_load_include('php', 'gavias_sliderlayer', '/includes/model');
  module_load_include('php', 'gavias_sliderlayer', '/includes/utilities');
  module_load_include('php', 'gavias_sliderlayer', '/includes/frontend');

function gavias_sliderlayer_theme($existing, $type, $theme, $path) {
  $items['admin-form'] = array(
    'variables' => array(
      'content' => '',
    ),
    'path' => $path . '/templates/backend',
  );

  $items['admin-global'] = array(
     'variables' => array(
      'content' => '',
    ),
     'path' => $path . '/templates/backend',
  );

  $items['block-slider'] = array(
     'variables' => array(
      'content' => '',
    ),
     'path' => $path . '/templates/frontend',
  );
  return $items;
}

function gavias_sliderlayer_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'gavias_sliderlayer/gavias_sliderlayer.assets.frontend';
}

function gavias_sliderlayer_styles(){
  $variables = array(
    'data' => array()
  );
  Drupal::moduleHandler()->alter('sliderlayer_styles', $variables);

  return $variables['data'];
}

function gavias_sliderlayer_update_projects_alter(&$projects){
   unset($projects['gavias_sliderlayer']);
}

